### ISSUE TITLE
Template option

### ISSUE THREAD

**Issue by matheusagcosta** [NikitaZanella/11ty-SASS#3]
@NikitaZanella Could you please mark this option under the settings? The `/generate` shortcut is throwing an error.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/3741582/188339381-542859a7-32c8-4ba3-b603-ff76f498113b.png">

**Comment by nktznl** [comment]
Woops! Done!
Thank you @matheusagcosta

**Comment by matheusagcosta** [comment]
Thank you! ⭐
